using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

// Editor-only boundary: no runtime state or Unity serialization is owned here.
internal sealed class BalanceCsvDocument
{
    internal static readonly string[] GoldKeys =
    {
        "NormalRoomGold", "LargeRoomGold", "WeaponPriceMin", "WeaponPriceMax",
        "CommonRelicPriceMin", "CommonRelicPriceMax", "RareRelicPriceMin", "RareRelicPriceMax",
        "EpicRelicPriceMin", "EpicRelicPriceMax", "ConsumablePriceMin", "ConsumablePriceMax"
    };

    internal bool ScalingEnabled;
    internal float HpIncrement;
    internal int[] Experience;
    internal Dictionary<string, int> Gold;

    internal static BalanceCsvDocument Read(string directory)
    {
        var stage = KeyValues(Path.Combine(directory, "StageHealth.csv"));
        RequireKeys(stage, new[] { "enabled", "hpMultiplierPerClearedStage" });
        if (stage["enabled"] != "0" && stage["enabled"] != "1")
            throw new FormatException("StageHealth.csv: enabled must be 0 or 1.");
        if (!float.TryParse(stage["hpMultiplierPerClearedStage"], NumberStyles.Float,
                CultureInfo.InvariantCulture, out float increment) ||
            float.IsNaN(increment) || float.IsInfinity(increment) || increment < 0f || increment > 100f)
            throw new FormatException("StageHealth.csv: HP increment must be finite and between 0 and 100.");

        var levels = Rows(Path.Combine(directory, "LevelExperience.csv"), "fromLevel", "requiredExperience");
        if (levels.Count == 0 || levels.Count > 999)
            throw new FormatException("LevelExperience.csv: expected 1..999 level rows.");
        var requirements = new int[levels.Count];
        var seen = new HashSet<int>();
        foreach (var row in levels)
        {
            int level = Positive(row[0], "fromLevel");
            if (level > levels.Count || !seen.Add(level))
                throw new FormatException("LevelExperience.csv: levels must be unique and consecutive from 1.");
            requirements[level - 1] = Positive(row[1], "requiredExperience");
        }

        var goldRows = KeyValues(Path.Combine(directory, "GoldEconomy.csv"));
        RequireKeys(goldRows, GoldKeys);
        var gold = new Dictionary<string, int>(StringComparer.Ordinal);
        foreach (string key in GoldKeys)
        {
            if (!int.TryParse(goldRows[key], NumberStyles.None, CultureInfo.InvariantCulture, out int value) ||
                value < 0 || value > 1000000)
                throw new FormatException($"GoldEconomy.csv: {key} must be an integer in 0..1000000.");
            gold.Add(key, value);
        }
        for (int i = 2; i < GoldKeys.Length; i += 2)
            if (gold[GoldKeys[i]] > gold[GoldKeys[i + 1]])
                throw new FormatException($"GoldEconomy.csv: {GoldKeys[i]} exceeds its maximum.");

        return new BalanceCsvDocument
        {
            ScalingEnabled = stage["enabled"] == "1", HpIncrement = increment,
            Experience = requirements, Gold = gold
        };
    }

    internal string GenerateGoldCode()
    {
        var text = new StringBuilder("// Generated by Tools/Balance Sheets/Apply CSV. Edit DataSheets/Balance/GoldEconomy.csv.\n");
        text.Append("public static class BalanceGoldValues\n{\n");
        foreach (string key in GoldKeys)
            text.Append("    public const int ").Append(key).Append(" = ")
                .Append(Gold[key].ToString(CultureInfo.InvariantCulture)).Append(";\n");
        return text.Append("}\n").ToString();
    }

    private static int Positive(string text, string name)
    {
        if (!int.TryParse(text, NumberStyles.None, CultureInfo.InvariantCulture, out int value) || value < 1)
            throw new FormatException($"{name} must be a positive integer.");
        return value;
    }

    private static Dictionary<string, string> KeyValues(string file)
    {
        var values = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var row in Rows(file, "key", "value"))
        {
            if (string.IsNullOrWhiteSpace(row[0]) || values.ContainsKey(row[0]))
                throw new FormatException($"{Path.GetFileName(file)}: empty or duplicate key '{row[0]}'.");
            values.Add(row[0], row[1]);
        }
        return values;
    }

    private static void RequireKeys(Dictionary<string, string> values, string[] keys)
    {
        if (values.Count != keys.Length)
            throw new FormatException("Unexpected or missing configuration keys.");
        foreach (string key in keys)
            if (!values.ContainsKey(key)) throw new FormatException($"Missing configuration key: {key}");
    }

    // The numeric authoring contract deliberately accepts only two columns, including Excel CSV quoting/BOM.
    private static List<string[]> Rows(string file, string first, string second)
    {
        var result = new List<string[]>();
        string[] lines = File.ReadAllLines(file, new UTF8Encoding(false, true));
        bool header = false;
        for (int i = 0; i < lines.Length; i++)
        {
            string line = lines[i].TrimStart('\uFEFF');
            if (string.IsNullOrWhiteSpace(line)) continue;
            string[] row = ParseLine(line, file, i + 1);
            if (!header)
            {
                if (row[0] != first || row[1] != second)
                    throw new FormatException($"{Path.GetFileName(file)}: expected header {first},{second}.");
                header = true;
            }
            else result.Add(row);
        }
        if (!header) throw new FormatException($"{Path.GetFileName(file)} is empty.");
        return result;
    }

    private static string[] ParseLine(string line, string file, int number)
    {
        var cells = new List<string>();
        var cell = new StringBuilder();
        bool quoted = false, closed = false;
        foreach (char c in line)
        {
            if (quoted)
            {
                if (c == '"') { quoted = false; closed = true; }
                else cell.Append(c);
            }
            else if (c == ',' )
            {
                cells.Add(cell.ToString()); cell.Clear(); closed = false;
            }
            else if (c == '"' && cell.Length == 0 && !closed) quoted = true;
            else if (closed || c == '"') throw new FormatException($"{file}:{number}: invalid CSV quoting.");
            else cell.Append(c);
        }
        cells.Add(cell.ToString());
        if (quoted || cells.Count != 2)
            throw new FormatException($"{file}:{number}: expected exactly two CSV columns.");
        return cells.ToArray();
    }
}
