"""Generate explicit asset keys from reviewed translations, without editing Unity assets.

Unreviewed entries are reported rather than filled with Korean placeholders.
Runtime identity is type/name/property; the translation key retains the asset GUID.
"""
import csv
import json
from pathlib import Path

folder = Path('DataSheets/Localization')
languages = ('ko', 'en', 'ja', 'zh-Hans', 'zh-Hant')
with (folder / 'CommonTranslations.tsv').open(encoding='utf-8-sig', newline='') as stream:
    reviewed = {r['ko'].replace('\\n', '\n').replace('\\r', '\r').replace('\\t', '\t'):
                {k: r[k].replace('\\n', '\n').replace('\\r', '\r').replace('\\t', '\t') for k in languages}
                for r in csv.DictReader(stream, delimiter='\t')}
with (folder / 'GameText.csv').open(encoding='utf-8-sig', newline='') as stream:
    rows = list(csv.DictReader(stream))
by_key = {r['key']: r for r in rows}
inventory = json.loads((folder / 'AssetInventory.json').read_text(encoding='utf-8'))['rows']
identities, missing, entries = {}, [], []
for asset in inventory:
    identity = '/'.join((asset['type'], asset['owner'], asset['field']))
    previous = identities.get(identity)
    if previous is not None and previous != asset['key']:
        raise ValueError('Ambiguous runtime asset identity: ' + identity)
    identities[identity] = asset['key']
    translation = reviewed.get(asset['text'])
    existing = by_key.get(asset['key'])
    if existing is not None and existing['ko'] != asset['text'].replace('N일', '{remaining_runs}'):
        raise ValueError('Authored text changed; review translations: ' + asset['key'])
    if existing is None:
        if translation is None or any(not translation[k].strip() for k in languages):
            missing.append(asset)
            continue
        existing = dict(key=asset['key'], **translation)
        rows.append(existing)
        by_key[asset['key']] = existing
    entries.append((identity, asset['key']))

with (folder / 'GameText.csv').open('w', encoding='utf-8-sig', newline='') as stream:
    writer = csv.DictWriter(stream, fieldnames=('key',) + languages)
    writer.writeheader()
    writer.writerows(rows)
(folder / 'UntranslatedAssets.json').write_text(
    json.dumps({'rows': missing}, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

def literal(value):
    return json.dumps(value, ensure_ascii=False)

source = ['using System.Collections.Generic;', '',
          '// Generated by Tools/Localization/expand_asset_keys.py. Do not match sentences at runtime.',
          'internal static class GameTextAssetKeys', '{',
          '    internal static readonly Dictionary<string, string> Keys = new()', '    {']
source += ['        { ' + literal(identity) + ', ' + literal(key) + ' },'
           for identity, key in sorted(entries)]
source += ['    };', '}', '']
Path('Assets/_Project/Runtime/Core/Presentation/GameTextAssetKeys.g.cs').write_text(
    '\n'.join(source), encoding='utf-8')
print(f'{len(entries)} reviewed asset fields connected; {len(missing)} fields await translation.')
