// Generated by Tools/Balance Sheets/Apply CSV. Edit DataSheets/Balance/GoldEconomy.csv.
public static class BalanceGoldValues
{
    public const int NormalRoomGold = 120;
    public const int LargeRoomGold = 180;
    public const int WeaponPriceMin = 1150;
    public const int WeaponPriceMax = 1250;
    public const int CommonRelicPriceMin = 400;
    public const int CommonRelicPriceMax = 500;
    public const int RareRelicPriceMin = 600;
    public const int RareRelicPriceMax = 700;
    public const int EpicRelicPriceMin = 900;
    public const int EpicRelicPriceMax = 1000;
    public const int ConsumablePriceMin = 850;
    public const int ConsumablePriceMax = 950;
}
